language: python
python:
- '3.6'
services:
- postgresql
env:
- DJANGO=3.1.7
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database attendance_management;' -U postgres
- python manage.py migrate --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: NK6BXP6sPRzf+yyohP0ICvsqdakl8idavhtEUFq1ls4s1Ddok7u1J/wak1hY8YjZqYdn7aiOzEEsYEoZk1onaLLvRIfdJXtPgyPzfacUOEdqFRDq/+jASQthRmsUB4KlfjwAE76tnt4Do8+4MeemVCORCzhmrZoBJEYEt+ptnOCiCNodn4uVOE3raNd4KTygInJxbDM9h064AM8qLKmC5vjf+Q5xQH8IWKVEeAsUaBTFQ/mWVeQ0re1z0IFZiiPKm/0M1vQJqMbZhMD5KZYf73rAplxvej4gcQRmTXaDpjP9toUx5NMpVUgyU0vY5xWCSiQsqW6JVU0YPN6gqGF2YO5xvW9tgZUp8CY1l4bccn292JKpEwXIdBm4KAZNxMqjvjAHnzkjyjpkb4QHMx6Jzuob4ZLJNTtvVF8hD5ebFS6kq/NTa5J4/7oaU4RTq4HSk1tO50iQ8V8v79lMyuiT8r2Uz6F6V5F1EfK6YXRcnuzKGh+NE9mHp5dJdSd82cOXvwj23gmXOFHwV+v0qwYvQPz4ZxE17iGaZhgj6UldG198kB0k9C4HNnJ2NpMYJ07x0+stR65xSi+2Fr5432dq+/sm2PjY9+aX6wqooDBjM+IkMkiEPPd4zYQqXoWM2LRU0V9kSLqprSJB7OvnOtFVz9Nqx3xh359YI6f584s6X4c=
  app: student-attendance-menegement
  on:
    repo: maks-nurgazy/diploma-project
  skip_cleanup: 'true'
