language: python
python:
- '3.8'
services:
- postgresql
env:
- DJANGO=3.1.7
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database attendance_management;' -U postgres
- python manage.py migrate --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: 5ffcdda0-c338-478b-84c1-4376016e40bf
  app: student-attendance-menegement
  on:
    repo: maks-nurgazy/diploma-project
  skip_cleanup: 'true'
