language: python
python:
- '3.8'
services:
- postgresql
env:
- DJANGO=3.1.7
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database attendance_management;' -U postgres
- python manage.py migrate --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: zuIq8RJWHP80EqqIgbxU6lLUDQVcL7xfaNxDAmzwNQfZw+tuGZJblBdDTOdF+u5X9qd2Ox7/HyE/rJxHQ0yXUlAVC34KV+/cRnukepVD2GXnxzxwWJagBqQWEEO0eMjGgvYNzDR8UuZ5cWwXZs6DI58/lFzSJXwRAcEKdFho+CyYjmUkpqXuWydq2CyLdp4luGkTIJwHHPB7u+p3PEQvwZY28zGp4zGE0EqSiU/zHkVULx7IuXe7cxVILwLXUkLsaz6LI6Ozw5ZJ0NV/umn09VA09YOD9GJvxhD80APZR4cBz2KwGlUjkOMUMSGDuPbp11NBFTqBZGO+hMEqUCNX8Q3IQ+ACGvLZ+JZsWIpCirBM29kgtSvC2y0UTaBHnt8tWg/9H3Yf8g7DkZkOJ5QqBMwJ1YdMtqcGvTFl2Op7rJe0nJlvXjBBQq+Y0heVuju3DMty1+D+44UAUVufjnFcvC4pMy4HqIReX3YCHGrMBvbHkk5O0qTqOTRiqXDJ/3cT+RXu8lM6MX1m4IIDq9z8Dlr/uoe9xVm1hLAsGDIcgXsrTQFiM+NGSmN8UGcFEMOaNVBg5bh5ON81qhYlSbUf8auAwhDfzRW5eSrcskld2LRVkOgp+DU4zzMTWGyQQ5XHC3Q6zxMQjZ0QLTweJLhMXW8+59SEWS21yD71AIwIQS0=
  app: student-attendance-menegement
  on:
    repo: maks-nurgazy/diploma-project
  skip_cleanup: 'true'
