language: python
python:
- '3.8'
services:
- postgresql
env:
- DJANGO=3.1.7
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database attendance_management;' -U postgres
- python manage.py migrate --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: dZg1TGx4Fipo9+2PujsH8VIAxmiNhLM0NNNt8IxHLigGW5uauXLJ8mBf2NWSTmiEZiUkp6jl10AWWEZEfaAnRBybIKIxvmpoRE5QC3OCR08eXa0zlc63c/tBAjIpBkmqmHC4OAn0rST1VG1sJCwjjfBjK4MfRlfZMcCRvy95h3jexBftDTv9I9ga+SoCeNIt+BCo5heJ1DNWokLf/LV5rg15WHWeNacAzL1rcEP7o0JHYS2LeFPiDneM3DBayD3DuY0w94G8WHXX56kHUkJgm+KBrvSvq1zIZh175bahyY1ytAz6PkhmznA4+SF0vXdGhtFPnCUZtNS5xSJa14tC0xxWZsKPWbuVGOXP8rhe7p9zhYcKtWfdBoXVqv7cqMOmJYP5pEa+Tk+N/DjovdUJ5Yx+TDlExEuNWXhArK5QAcY0BCWJ+k2yDA45Rn9gFrM1m2n2l7FQUpwd6lMsYY1VTtCtvTt9kESo1UuTR40VM5qpJUoj7d03OGscCJ4PMlRHw30CpUl0Rg17JQybQJuu0COWXq7k3QzUE6ojySsMVzQDxRHE6yWR5GjMFgOl5rs40iy7blon9yJIcVSMQ31hNPcKzpz3x75bRcnhmSOGDLgrCFdXBYibAj8iugraLM3u6+IpQeZTq5JYs2Lfjn1LXopQuU0cR2ClHGHkMLUiv1U=
  app: student-attendance-menegement
  on:
    repo: maks-nurgazy/diploma-project
  skip_cleanup: 'true'
